const users = require("./users");
const root = require("./root");
const homePage = require("./homepage");
const college = require("./college");
const jobs = require("./jobs");
const states = require("./states");
const news = require("./news");
const course = require("./course");
module.exports = { users, root, homePage, college, jobs, states, news, course, states };
