const users = require("./users");
const homepage = require("./homepage");
const college = require("./college");
const jobs = require("./jobs");
const news = require("./news");
const states = require("./states");
const course = require("./course");
const search = require("./search");
const exam = require("./exam")
module.exports = { users, homepage, college, jobs, news, states, course,search, exam };
